apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: skaffold-example
build:
  artifacts:
    - image: skaffold_example_test
  local:
    push: false
manifests:
  helm:
    releases:
      - name: my-app
        chartPath: ./helm-chart
        valuesFiles:
          - ./helm-chart/values.yaml
        setValueTemplates:
          # use skaffold-generated image repo and tag for our deployment
          image.repository: "{{ .IMAGE_REPO_skaffold_example_test }}"
          image.tag: "{{ .IMAGE_TAG_skaffold_example_test }}"
deploy:
  kubeContext: minikube
portForward:
  - resourceType: deployment
    resourceName: my-app
    port: 8080
    address: 0.0.0.0
    localPort: 9000
