apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "my-app.fullname" . }}
  labels:
    app: {{ include "my-app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-app.fullname" . }}
    spec:
      containers:
        - name: my-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
